### ISSUE TITLE
__typename for `.js` files

### ISSUE THREAD

**Issue by mergebandit** [sysgears/persistgraphql-webpack-plugin#15] opened 2017-10-17 18:07 UTC
I've got a mixture of `gql` files (fragments & mutations) and `.js` files (queries) using the `gql` template literal tag. My plugin is configured with the `addTypename: true` property.

After setting this up, I am running into the `Could not find query inside query map` error that's coming out of [persistgraphql](https://github.com/apollographql/persistgraphql/blob/master/src/network_interface/ApolloNetworkInterface.ts#L64).

Inspecting my code, the query I'm sending has `__typename` on all of my schema types. The query map only includes `__typename` for `.gql|.graphql` files, but not for queries wrapped in the `gql` template tag literal within `.js` files.

So I started digging through your source code, and noticed that the only time you actually run the add typename transformer is on `.gql|.graphql` files [seen here](https://github.com/sysgears/persistgraphql-webpack-plugin/blob/master/index.js#L85). If the query was pulled from a `.js` file using the `gql` template literal tag, that `addTypenameTransformer` is never executed.

Is this expected behavior?

**Comment by larixer** [comment] 2017-10-18 07:19
@mergebandit This is a plugin on top of https://github.com/apollographql/persistgraphql And if `persistgraphql` doesn't apply query transformers on top of gql queries in JS files, there is no way this plugin can do, because in this case the format of generated extracted queries `json` file will be different. Usually we are hard to fix the bug, even when minimum information is available in issue report. But this is not the case for `persistgraphql-webpack-plugin`, since it is vital to keep the same format of generated queries as in `persistgraphql`. So, if you want us to look at your case, please provide minimal reproduction example for us to look.

**Comment by larixer** [comment] 2017-10-18 07:28
@mergebandit Please disregard, I see that latest version of `persistgraphql` reparses and reapplies transformers on all it's output at the end

**Comment by larixer** [comment] 2017-10-18 08:00
@mergebandit Should be fixed in `persistgraphql-webpack-plugin@0.4.3`

**Closed as completed** 2017-10-18 07:59 UTC

**Comment by mergebandit** [comment] 2017-10-19 18:53
Since updating to `0.4.3`, I'm getting a bunch of `Cannot read property 'kind' of null` errors. It seems my `.js` fragments aren't being given document definitions. For example, I have this query:

```
  query Layout($guestId: BigInt!, $stayId: BigInt!, $language: String!) {
    guest(guestId: $guestId, language: $language) {
      guestId
      upcomingStay(stayId: $stayId) {
        checkinEligibilityStatus
        ...MetricsFragment
      }
      ...HeaderFragment
      ...FooterFragment
      ...TimeoutModalFragment
    }
  }
  ${HeaderFragment}
  ${FooterFragment}
  ${MetricsFragment}
  ${TimeoutModalFragment}
```

If I log out the document, get definitions for my layout query, but the subsequent fragment definitions are all null.

Any thoughts on why?

Here's the full stack:

```
TypeError: Cannot read property 'kind' of null
    at /Users/mergebandit/dev/projectX/node_modules/persistgraphql/src/queryTransformers.ts:66:30
    at Array.forEach (<anonymous>)
    at exports.addTypenameTransformer (/Users/mergebandit/dev/projectX/node_modules/persistgraphql/src/queryTransformers.ts:65:24)
    at ExtractGQL.queryTransformers (/Users/mergebandit/dev/projectX/node_modules/persistgraphql-webpack-plugin/index.js:118:22)
    at /Users/mergebandit/dev/projectX/node_modules/persistgraphql/src/common.ts:63:23
    at Array.forEach (<anonymous>)
    at Object.applyQueryTransformers (/Users/mergebandit/dev/projectX/node_modules/persistgraphql/src/common.ts:62:21)
    at ExtractGQL.applyQueryTransformers (/Users/mergebandit/dev/projectX/node_modules/persistgraphql/src/ExtractGQL.ts:129:12)
    at ExtractGQL.createMapFromDocument (/Users/mergebandit/dev/projectX/node_modules/persistgraphql/src/ExtractGQL.ts:149:38)
    at /Users/mergebandit/dev/projectX/node_modules/persistgraphql/src/ExtractGQL.ts:182:19
    at Array.map (<anonymous>)
    at ExtractGQL.createOutputMapFromString (/Users/mergebandit/dev/projectX/node_modules/persistgraphql/src/ExtractGQL.ts:180:44)
    at Compilation.<anonymous> (/Users/mergebandit/dev/projectX/node_modules/persistgraphql-webpack-plugin/index.js:121:39)
    at Compilation.applyPlugins0 (/Users/mergebandit/dev/projectX/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/Users/mergebandit/dev/projectX/node_modules/webpack/lib/Compilation.js:567:8)
    at applyPluginsParallel.err (/Users/mergebandit/dev/projectX/node_modules/webpack/lib/Compiler.js:508:17)
```

**Comment by larixer** [comment] 2017-10-20 03:15
@mergebandit Does running `persistgraphql` on your source code and gathering queries from '.js' files work well?

https://github.com/apollographql/persistgraphql#extracting-queries-from-javascript
